services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - backend
    restart: always

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - /docker/wordpress:/var/www
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "${PHPMYADMIN_HTTP_PORT}:80"
    env_file:
      - .env
    networks:
      - frontend
      - backend
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "${WORDPRESS_HTTP_PORT}:443"
    volumes:
      - /docker/nginx:/etc/nginx/conf.d
      - /docker/ssl:/etc/nginx/ssl
      - /docker/wordpress:/var/www
    depends_on:
      - wordpress
    networks:
      - frontend
      - backend
    restart: always

volumes:
    db_data: {}

networks:
    frontend:
    backend:
